/* Generated by dev/build_tools.py. Don't edit by hand; run python3 dev/build_tools.py instead.
   Lets Sharp work offline: pages come from the internet when possible (and are saved), otherwise from the saved copy.
   Never touches /api/ (AI helpers) or /course/ (paid content). Nothing a visitor types is ever sent or stored here. */
var VERSION = 'sharp-6837f368e2f7';
var FILES = [
"./404.html",
"./about/",
"./app.js",
"./apple-touch-icon.png",
"./ask/ask.js",
"./ask/",
"./assets/fonts.css",
"./assets/fonts/-F63fjptAgt5VM-kVkqdyU8n1i8q1w.woff2",
"./assets/fonts/-F63fjptAgt5VM-kVkqdyU8n1iEq129k.woff2",
"./assets/fonts/-F6qfjptAgt5VM-kVkqdyU8n3twJwl5FgtIU.woff2",
"./assets/fonts/-F6qfjptAgt5VM-kVkqdyU8n3twJwlBFgg.woff2",
"./assets/fonts/-F6qfjptAgt5VM-kVkqdyU8n3vAOwl5FgtIU.woff2",
"./assets/fonts/-F6qfjptAgt5VM-kVkqdyU8n3vAOwlBFgg.woff2",
"./assets/fonts/3y9K6as8bTXq_nANBjzKo3IeZx8z6up5BeSl9D4dj_x9PpZBMlGGInHEVA.woff2",
"./assets/fonts/3y9K6as8bTXq_nANBjzKo3IeZx8z6up5BeSl9D4dj_x9PpZBMlGIInE.woff2",
"./assets/fonts/Wnz6HAc5bAfYB2Q7ZjYY.woff2",
"./assets/fonts/Wnz6HAc5bAfYB2Q7aDYYmg8.woff2",
"./assets/fonts/qkB9XvYC6trAT55ZBi1ueQVIjQTD-JrIH2G7nytkHRyQ8p4wUje6bg.woff2",
"./assets/fonts/qkB9XvYC6trAT55ZBi1ueQVIjQTD-JrIH2G7nytkHRyQ8p4wUjm6bnEr.woff2",
"./assets/fonts/qkBKXvYC6trAT7RQNNK2EG7SIwPWMNlCV3lGb7PnGw.woff2",
"./assets/fonts/qkBKXvYC6trAT7RQNNK2EG7SIwPWMNlCV3lIb7M.woff2",
"./assets/quotes.js",
"./assets/sharp.css",
"./assets/shell.js",
"./assets/tools.js",
"./books/",
"./config.js",
"./icon-192.png",
"./icon-512.png",
"./icon-maskable-512.png",
"./icon.svg",
"./",
"./learn/app.js",
"./learn/early.js",
"./learn/",
"./learn/today.js",
"./manifest.webmanifest",
"./plan/",
"./plan/plan.js",
"./pricing/",
"./privacy/",
"./refunds/",
"./shots/fit-390.png",
"./terms/",
"./tools/ai/",
"./tools/budget/budget.js",
"./tools/budget/",
"./tools/business-plan/",
"./tools/idea-check/",
"./tools/",
"./tools/investors/",
"./tools/marketing/",
"./tools/money-plan/",
"./tools/negotiation/",
"./trial/",
"./trial/trial.js"
];
self.addEventListener('install', function(e){
  e.waitUntil(caches.open(VERSION).then(function(c){ return c.addAll(FILES); }).then(function(){ return self.skipWaiting(); }));
});
self.addEventListener('activate', function(e){
  e.waitUntil(caches.keys().then(function(keys){
    return Promise.all(keys.filter(function(k){ return k.indexOf('sharp-') === 0 && k !== VERSION; }).map(function(k){ return caches.delete(k); }));
  }).then(function(){ return self.clients.claim(); }));
});
// The same page can be asked for as /learn/ or /learn/index.html.
function variants(url){
  var u = new URL(url); u.hash = ''; u.search = '';
  var a = [u.href];
  if(/\/index\.html$/.test(u.pathname)) a.push(u.href.replace(/index\.html$/, ''));
  else if(/\/$/.test(u.pathname)) a.push(u.href + 'index.html');
  return a;
}
function fromCache(req){
  var v = variants(req.url), i = 0;
  return caches.open(VERSION).then(function(c){
    function next(){ if(i >= v.length) return undefined; return c.match(v[i++]).then(function(r){ return r || next(); }); }
    return next();
  });
}
self.addEventListener('fetch', function(e){
  var req = e.request, url = new URL(req.url);
  if(req.method !== 'GET' || url.origin !== self.location.origin) return;
  var scope = new URL(self.registration.scope).pathname, path = url.pathname.slice(scope.length - 1);
  if(path.indexOf('/api/') === 0 || path.indexOf('/course/') === 0) return;
  if(req.mode === 'navigate'){
    // Pages: fresh from the internet first, saved copy when offline.
    e.respondWith(fetch(req).then(function(res){
      if(res.ok && !res.redirected){ var copy = res.clone(); caches.open(VERSION).then(function(c){ c.put(variants(req.url)[0], copy); }); }
      return res;
    }).catch(function(){
      return fromCache(req).then(function(r){
        return r || new Response('<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Offline · Sharp Basics</title><body style="font-family:system-ui;background:#0d1020;color:#f2f3f9;padding:32px;line-height:1.5"><h1>You\'re offline</h1><p>This page isn\'t saved on this device yet. Connect to the internet and try again.</p><p><a style="color:#ff8f5e" href="' + scope + '">Go to the home page</a></p>', { status: 503, headers: { 'content-type': 'text/html; charset=utf-8' } });
      });
    }));
    return;
  }
  // Files (styles, scripts, fonts, icons): saved copy straight away, refreshed in the background.
  e.respondWith(fromCache(req).then(function(hit){
    var net = fetch(req).then(function(res){
      if(res.ok){ var copy = res.clone(); caches.open(VERSION).then(function(c){ c.put(variants(req.url)[0], copy); }); }
      return res;
    });
    if(hit){ net.catch(function(){}); return hit; }
    return net;
  }));
});
